server:
  port: 8761

eureka:
  instance:
    hostname: service-registry
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: service-registry
  cloud:
    inetutils:
      preferred-networks: 172.